name: ${project.name}
version: ${project.version}
website: ${project.url}
description: ${project.description}
authors: [JustMatt <matt@matthogan.co.uk>, SimplePlugins <github.com/SimplePlugins>]

main: ${project.groupId}.${project.artifactId}.${project.name}Plugin